_extends: .github

repository:
  name: directory-anarchy
  description: A directory traversal game that teaches you Bash
  homepage: anarchy.aperiodicity.com

  # A comma-separated list of topics to set on the repository
  topics: settings
  private: false