fail_fast: true
repos:
  # Requires hadolint binary on local machine.
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        args:
          - --config
          - config/.hadolint.yaml
          - Dockerfile

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=10000, --enforce-all]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        args:
          - -x

  - repo: https://github.com/emmeowzing/dynamic-continuation-orb
    rev: v3.6.8
    hooks:
      - id: circleci-config-validate

  - repo: https://github.com/premiscale/pre-commit-hooks
    rev: v0.0.7
    hooks:
    -   id: msg-issue-prefix