version: 2.1

orbs:
  shellcheck: circleci/shellcheck@3.3.0

executors:
  default:
    docker:
      - image: cimg/base:stable

workflows:
  version: 2

  on-commit:
    jobs:
      - shellcheck/check:
          dir: .
          exclude: SC2148
          filters:
            branches:
              ignore: master
